(()=>{
const MODS=[
{id:'9001',code:'ISO 9001',edition:'2015 + Amd 1:2024',name:'Gestión de la calidad',domain:'Calidad',active:true},
{id:'14001',code:'ISO 14001',edition:'2026',name:'Gestión ambiental',domain:'Ambiente',active:false},
{id:'45001',code:'ISO 45001',edition:'2018 + Amd 1:2024',name:'Seguridad y salud en el trabajo',domain:'SST',active:false}
];
const Q={
'9001':`4.1|Contexto interno y externo relevante;4.2|Partes interesadas y necesidades pertinentes;4.3|Alcance del sistema de calidad;4.4.1|Procesos e interacciones del sistema;4.4.2|Información documentada de procesos;5.1.1|Liderazgo y compromiso;5.1.2|Enfoque al cliente;5.2.1|Política de calidad;5.2.2|Comunicación de la política;5.3|Responsabilidades y autoridades;6.1|Riesgos y oportunidades;6.2.1|Objetivos de calidad;6.2.2|Planificación para lograr objetivos;6.3|Planificación de cambios;7.1.1|Recursos;7.1.2|Personas;7.1.3|Infraestructura;7.1.4|Ambiente para la operación;7.1.5.1|Recursos de seguimiento y medición;7.1.5.2|Trazabilidad metrológica;7.1.6|Conocimiento organizacional;7.2|Competencia;7.3|Toma de conciencia;7.4|Comunicación;7.5.1|Información documentada necesaria;7.5.2|Creación y actualización documental;7.5.3|Control de información documentada;8.1|Planificación y control operacional;8.2.1|Comunicación con clientes;8.2.2|Requisitos de productos y servicios;8.2.3|Revisión de requisitos;8.2.4|Cambios en requisitos;8.3.1|Diseño y desarrollo;8.3.2|Planificación del diseño;8.3.3|Entradas de diseño;8.3.4|Controles de diseño;8.3.5|Resultados de diseño;8.3.6|Cambios de diseño;8.4.1|Control de provisión externa;8.4.2|Tipo y alcance de controles externos;8.4.3|Información a proveedores externos;8.5.1|Producción y prestación controlada;8.5.2|Identificación y trazabilidad;8.5.3|Propiedad de clientes/proveedores;8.5.4|Preservación;8.5.5|Actividades posteriores a entrega;8.5.6|Control de cambios;8.6|Liberación de productos y servicios;8.7.1|Salidas no conformes;8.7.2|Evidencia de no conformidades;9.1.1|Seguimiento y medición;9.1.2|Satisfacción del cliente;9.1.3|Análisis y evaluación;9.2.1|Auditoría interna;9.2.2|Programa de auditorías;9.3.1|Revisión por la dirección;9.3.2|Entradas de revisión;9.3.3|Resultados de revisión;10.1|Oportunidades de mejora;10.2.1|No conformidad y acción correctiva;10.2.2|Evidencia de acciones correctivas;10.3|Mejora continua`,
'14001':`4.1|Contexto ambiental;4.2|Partes interesadas y obligaciones;4.3|Alcance ambiental;4.4|Sistema ambiental;5.1|Liderazgo ambiental;5.2|Política ambiental;5.3|Roles y responsabilidades;6.1.1|Riesgos y oportunidades;6.1.2|Aspectos ambientales;6.1.3|Obligaciones de cumplimiento;6.1.4|Planificación de acciones;6.2|Objetivos ambientales;7.1|Recursos;7.2|Competencia;7.3|Toma de conciencia;7.4|Comunicación;7.5|Información documentada;8.1|Control operacional;8.2|Preparación y respuesta ante emergencias;9.1|Seguimiento y evaluación;9.1.2|Evaluación del cumplimiento;9.2|Auditoría interna;9.3|Revisión por la dirección;10.2|No conformidad y acción correctiva;10.3|Mejora continua`,
'45001':`4.1|Contexto de SST;4.2|Trabajadores y partes interesadas;4.3|Alcance del sistema de SST;4.4|Sistema de SST;5.1|Liderazgo y compromiso;5.2|Política de SST;5.3|Roles y responsabilidades;5.4|Consulta y participación;6.1.1|Riesgos y oportunidades;6.1.2.1|Identificación de peligros;6.1.2.2|Evaluación de riesgos de SST;6.1.2.3|Oportunidades de SST;6.1.3|Requisitos legales y otros;6.1.4|Planificación de acciones;6.2|Objetivos de SST;7.1|Recursos;7.2|Competencia;7.3|Toma de conciencia;7.4|Comunicación;7.5|Información documentada;8.1.1|Control operacional;8.1.2|Eliminar peligros y reducir riesgos;8.1.3|Gestión del cambio;8.1.4|Compras y contratistas;8.2|Emergencias;9.1.1|Seguimiento del desempeño;9.1.2|Evaluación del cumplimiento;9.2|Auditoría interna;9.3|Revisión por la dirección;10.2|Incidentes y acciones correctivas;10.3|Mejora continua`
};
const parse=(id)=>Q[id].split(';').map((x,i)=>{const [ref,summary]=x.split('|');return{id,ref,summary,process:i%5!==0,document:i%4!==0,evidence:i%3!==0,status:i%7===0?'gap':i%5===0?'partial':'covered'}});
const requirements=Object.keys(Q).flatMap(parse);
try{const s=JSON.parse(localStorage.getItem('sig-modules')||'{}');MODS.forEach(m=>{if(s[m.id]!=null)m.active=!!s[m.id]})}catch{}
const save=()=>localStorage.setItem('sig-modules',JSON.stringify(Object.fromEntries(MODS.map(m=>[m.id,m.active]))));
const active=()=>MODS.filter(m=>m.active), activeReq=()=>requirements.filter(r=>active().some(m=>m.id===r.id));
const content=document.querySelector('.content');if(content&&!document.getElementById('standards'))content.insertAdjacentHTML('beforeend','<section id="standards" class="view"></section>');
const baseRenderNav=window.renderNav,baseGo=window.go,baseRender=window.render,baseHome=window.renderHome,baseReq=window.renderReq;
window.renderNav=function(){if(role!=='admin')return baseRenderNav();const admin=[['Diseño'],['home','⌂','Inicio'],['map','⌘','Arquitectura'],['processes','◫','Procesos'],['standards','▦','Módulos / Normas'],['requirements','◎','Requisitos'],['risks','◇','Riesgos'],['versions','◷','Publicaciones'],['Sistema'],['documents','▤','Documentos'],['evidence','✓','Evidencias'],['actions','↗','Mejora'],['settings','⚙','Configuración']];nav.innerHTML=admin.map(x=>x.length===1?`<div class="navlabel">${x[0]}</div>`:`<nav class="nav"><button data-v="${x[0]}" onclick="go('${x[0]}')"><span>${x[1]}</span><span>${x[2]}</span></button></nav>`).join('')};
window.go=function(v){if(role==='admin'&&v==='standards'){view=v;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));standards.classList.add('active');document.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===v));renderStandards();return}return baseGo(v)};
window.render=function(v){if(v==='standards')return renderStandards();return baseRender(v)};
window.renderHome=function(){baseHome();if(role!=='admin')return;const h=document.getElementById('home');const head=h.querySelector('.head>div');if(head&&!head.querySelector('.modulechips'))head.insertAdjacentHTML('beforeend',`<div class="modulechips" style="margin-top:8px">${active().map(m=>`<span class="modulechip">${m.code} ${m.edition}</span>`).join('')}</div>`)};
window.toggleSigModule=id=>{const m=MODS.find(x=>x.id===id);if(!m)return;m.active=!m.active;save();renderStandards()};
window.renderStandards=function(){const el=document.getElementById('standards');el.innerHTML=`${banner()}<div class="head"><div><div class="eyebrow">CONFIGURACIÓN MODULAR</div><h1>Módulos y normas</h1><p>Activá sólo los sistemas que la organización quiera implementar. Todos trabajan sobre los mismos procesos, documentos y evidencias.</p></div></div><div class="copyrightnote"><div class="iicon" style="background:#fff1c8;color:#8a6417">i</div><div><strong>Catálogo estructurado sí; texto oficial completo, sólo con licencia.</strong><p>La demo usa referencias y resúmenes operativos. Una copia licenciada podrá vincular el texto oficial.</p></div></div><div class="modulegrid">${MODS.map(m=>`<div class="card modulecard ${m.active?'active':''}"><div class="moduletop"><div><div class="modulecode">${m.code}</div><div class="tiny">${m.edition}</div></div><span class="badge ${m.active?'g':''}">${m.active?'Activo':'Inactivo'}</span></div><h3 style="margin:12px 0 4px">${m.name}</h3><p>${m.domain}. Un único sistema organizacional con esta norma como capa de requisitos.</p><div class="modulemeta"><div><span>Catálogo</span><strong>${requirements.filter(r=>r.id===m.id).length} requisitos</strong></div><div><span>Modo</span><strong>Modular</strong></div></div><div class="moduleactions"><span class="tiny">Afecta cobertura y publicación.</span><button class="toggle ${m.active?'on':''}" onclick="toggleSigModule('${m.id}')">${m.active?'Desactivar':'Activar'}</button></div></div>`).join('')}</div>`};
window.renderReq=function(){if(role!=='admin')return baseReq();const mods=active(),rs=activeReq(),covered=rs.filter(r=>r.status==='covered').length,gaps=rs.filter(r=>r.status==='gap').length;requirementsEl().innerHTML=`${banner()}<div class="head"><div><div class="eyebrow">COBERTURA</div><h1>Requisitos</h1><p>Matriz completa de los módulos activos, con aplicabilidad y trazabilidad de cumplimiento.</p><div class="modulechips" style="margin-top:8px">${mods.map(m=>`<span class="modulechip">${m.code} ${m.edition}</span>`).join('')}</div></div><button class="btn secondary" onclick="go('standards')">Gestionar módulos</button></div><div class="grid g4"><div class="card pad metric"><label>Módulos activos</label><strong>${mods.length}</strong></div><div class="card pad metric"><label>Requisitos catalogados</label><strong>${rs.length}</strong></div><div class="card pad metric"><label>Cubiertos</label><strong>${covered}</strong></div><div class="card pad metric"><label>Brechas</label><strong>${gaps}</strong></div></div><div class="copyrightnote"><div class="iicon" style="background:#fff1c8;color:#8a6417">§</div><div><strong>Los resúmenes no sustituyen la norma oficial.</strong><p>Cada fila representa un requisito evaluable y conserva referencia, proceso, documento, evidencia y estado.</p></div></div>${rs.length?`<div class="card pad tablewrap"><div class="filterbar"><select id="reqStd" onchange="renderSigReqRows()"><option value="all">Todos los módulos</option>${mods.map(m=>`<option value="${m.id}">${m.code}</option>`).join('')}</select><select id="reqStatus" onchange="renderSigReqRows()"><option value="all">Todos los estados</option><option value="covered">Cubierto</option><option value="partial">Parcial</option><option value="gap">Brecha</option></select><input id="reqSearch" placeholder="Buscar referencia o requisito…" oninput="renderSigReqRows()"></div><div id="sigReqRows" class="reqtable"></div></div>`:'<div class="card emptyreq">No hay módulos activos. Activá al menos uno en Módulos / Normas.</div>'}`;if(rs.length)renderSigReqRows()};
function requirementsEl(){return document.getElementById('requirements')}
window.renderSigReqRows=function(){const std=reqStd?.value||'all',st=reqStatus?.value||'all',q=(reqSearch?.value||'').toLowerCase(),mods=new Map(active().map(m=>[m.id,m]));const rows=activeReq().filter(r=>(std==='all'||r.id===std)&&(st==='all'||r.status===st)&&(!q||(`${r.ref} ${r.summary}`).toLowerCase().includes(q)));sigReqRows.innerHTML=`<div class="reqhead"><div>Referencia</div><div>Requisito / resumen</div><div>Aplicabilidad</div><div>Proceso</div><div>Documento</div><div>Evidencia</div><div>Estado</div></div>${rows.map(r=>`<div class="reqrow"><div><strong>${mods.get(r.id)?.code||''}</strong><div class="tiny">${r.ref}</div></div><div class="reqsum">${r.summary}</div><div><span class="badge g">Aplica</span></div><div><span class="badge ${r.process?'g':'r'}">${r.process?'Vinculado':'Falta'}</span></div><div><span class="badge ${r.document?'g':'r'}">${r.document?'Vinculado':'Falta'}</span></div><div><span class="badge ${r.evidence?'g':'r'}">${r.evidence?'Existe':'Falta'}</span></div><div><span class="badge ${r.status==='covered'?'g':r.status==='partial'?'a':'r'}">${r.status==='covered'?'Cubierto':r.status==='partial'?'Parcial':'Brecha'}</span></div></div>`).join('')||'<div class="emptyreq">Sin resultados.</div>'}`};
if(role){renderNav();if(view==='requirements')renderReq();else if(view==='home')renderHome()}
})();
